version: '3.8'

services:
  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - hotel-network

  hotel-service:
    build:
      context: .
      dockerfile: ./hotel-service/Dockerfile
    container_name: hotel-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - hotel-network
    restart: on-failure

  booking-service:
    build:
      context: .
      dockerfile: ./booking-service/Dockerfile
    container_name: booking-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - hotel-service
    networks:
      - hotel-network
    restart: on-failure

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - booking-service
      - hotel-service
    networks:
      - hotel-network
    restart: on-failure

networks:
  hotel-network:
    driver: bridge